
levelsof importer, clean local(cty)

local r "replace ccode1 = "


`r' 305 if "`cty'"=="Austria"
`r' 53 if "`cty'"=="Barbados"
`r' 155 if "`cty'"=="Chile"
`r' 100 if "`cty'"=="Colombia"
`r' 94 if "`cty'"=="Costa Rica"
`r' 225 if "`cty'"=="Switzerland"
`r' 200 if "`cty'"=="United Kingdom" | "`cty'"=="UK"
`r'  2 if "`cty'"=="US"
`r' 160 if "`cty'"=="Argentina"
`r' 900 if "`cty'"=="Australia"
`r' 101 if "`cty'"=="Venezuela"
`r' 165 if "`cty'"=="Uruguay"
`r' 130 if "`cty'"=="Ecuador"
`r' 385 if "`cty'"=="Norway"
`r' 360 if "`cty'"=="Romania"
`r' 220 if "`cty'"=="France"
`r' 135 if "`cty'"=="Peru"
`r' 210 if "`cty'"=="Netherlands"
`r' 339 if "`cty'"=="Albania"
`r' 750 if "`cty'"=="India"
`r' 40 if "`cty'"=="Cuba"
`r' 640 if "`cty'"=="Turkey"
`r' 255 if "`cty'"=="Germany"
`r' 110 if "`cty'"=="British Guiana"
`r' 345 if "`cty'"=="Yugoslavia"
`r' 380 if "`cty'"=="Sweden"
`r' 325 if "`cty'"=="Italy"
`r' 740 if "`cty'"=="Japan"
`r' 115 if "`cty'"=="Suriname"
`r' 56 if "`cty'"=="St Lucia"
`r' 55 if "`cty'"=="Grenada"
`r' 475 if "`cty'"=="Nigeria"
`r' 70 if "`cty'"=="Mexico"
`r' 390 if "`cty'"=="Denmark"
`r' 20 if "`cty'"=="Canada"
`r' 290 if "`cty'"=="Poland"
`r' 145 if "`cty'"=="Bolivia"
`r' 366 if "`cty'"=="Estonia"
`r' 616 if "`cty'"=="Tunisia"
`r' 355 if "`cty'"=="Bulgaria"
`r' 211 if "`cty'"=="Belgium"
`r' 651 if "`cty'"=="Egypt"
`r' 490 if "`cty'"=="Belgian-Kongo"
`r' 42 if "`cty'"=="Dominican Republic"
`r' 52 if "`cty'"=="Trinidad"
`r' 710 if "`cty'"=="China"
`r' 30 if "`cty'"=="Bermuda"
`r' 560 if "`cty'"=="South Africa"
`r' 551 if "`cty'"=="Northern Rhodesia"
`r' 552 if "`cty'"=="Southern Rhodesia"
`r' 565 if "`cty'"=="Southwest Africa"
`r' 367 if "`cty'"=="Latvia"
`r' 368 if "`cty'"=="Lithuania"
`r' 140 if "`cty'"=="Brazil"
`r' 515 if "`cty'"=="Ruanda-Urundi"
`r' 92 if "`cty'"=="Salvador"
`r' 840 if "`cty'"=="Philippines"
`r' 590 if "`cty'"=="Mauritius"
`r' 338 if "`cty'"=="Malta"
`r' 820 if "`cty'"=="British Malaya"
`r' 505 if "`cty'"=="Kenya and Uganda"
`r' 352 if "`cty'"=="Cyprus"
`r' 80 if "`cty'"=="British Honduras"
`r' 800 if "`cty'"=="Thailand"
`r' 591 if "`cty'"=="Seychelles"
`r' 910 if "`cty'"=="Papua"
`r' 93 if "`cty'"=="Nicaragua"
`r' 235 if "`cty'"=="Portugal"
`r' 315 if "`cty'"=="Czechoslovakia"
`r' 395 if "`cty'"=="Iceland"
`r' 205 if "`cty'"=="Ireland"
`r' 920 if "`cty'"=="New Zealand"
`r' 90 if "`cty'"=="Guatemala"
`r' 541 if "`cty'"=="Mozambique"
`r' 51 if "`cty'"=="Jamaica"
`r' 553 if "`cty'"=="Nyasaland"
`r' 95 if "`cty'"=="Panama"
`r' 310 if "`cty'"=="Hungary"
`r' 150 if "`cty'"=="Paraguay"
`r' 91 if "`cty'"=="Honduras"
`r' 850 if "`cty'"=="Dutch East Indies"
`r' 990 if "`cty'"=="Western Samoa"
`r' 652 if "`cty'"=="Syria-Lebanon"
`r' 461 if "`cty'"=="Togo"
`r' 41 if "`cty'"=="Haiti"
`r' 645 if "`cty'"=="Iraq"
`r' 511 if "`cty'"=="Zanzibar"
`r' 625 if "`cty'"=="Sudan"
`r' 375 if "`cty'"=="Finland"
`r' 420 if "`cty'"=="Gambia"
`r' 452 if "`cty'"=="Gold Coast"
`r' 510 if "`cty'"=="Tanganyika"
`r' 451 if "`cty'"=="Sierra Leone"
`r' 350 if "`cty'"=="Greece"
`r' 810 if "`cty'"=="French Indochina"
`r' 450 if "`cty'"=="Liberia"
`r' 950 if "`cty'"=="Fiji"
`r' 230 if "`cty'"=="Spain"
`r' 830 if "`cty'"=="Singapore"
`r' 720 if "`cty'"=="Hong Kong"
`r' 780 if "`cty'"=="Ceylon"
`r' 573 if "`cty'"=="British South Africa"
`r' 365 if "`cty'"=="Russia"


